import { fontStack } from "@/lib/typography/css";
import { googleFontsCssUrl, googleFontsEmbed } from "@/lib/typography/google-fonts";
import { generateScale } from "@/lib/typography/scale";
import type { ExportFormat } from "@/types/export";
import type { FontFamily, OpenTypeSettings, TextRhythm, TypeScaleSettings, TypeScaleStep } from "@/types/typography";

export type TypographyExportInput = {
  heading: FontFamily;
  body: FontFamily;
  scale: TypeScaleSettings;
  rhythm: TextRhythm;
  openType: OpenTypeSettings;
};

type Resolved = TypographyExportInput & { steps: TypeScaleStep[]; features: string[] };

function resolve(input: TypographyExportInput): Resolved {
  const features = (Object.entries(input.openType) as [string, boolean][])
    .filter(([tag, on]) => on && tag !== "liga" && tag !== "kern")
    .map(([tag]) => tag);
  return { ...input, steps: generateScale(input.scale), features };
}

const uniqueFonts = (r: Resolved) => (r.heading.family === r.body.family ? [r.heading] : [r.heading, r.body]);

function css(r: Resolved): string {
  const featureLine = r.features.length
    ? `\n  font-feature-settings: ${r.features.map((f) => `"${f}"`).join(", ")};`
    : "";
  return `@import url("${googleFontsCssUrl(uniqueFonts(r))}");

:root {
  --font-heading: ${fontStack(r.heading.family, r.heading.category)};
  --font-body: ${fontStack(r.body.family, r.body.category)};

  --font-weight-heading: ${r.rhythm.headingWeight};
  --font-weight-body: ${r.rhythm.bodyWeight};
  --leading-heading: ${r.rhythm.headingLineHeight};
  --leading-body: ${r.rhythm.bodyLineHeight};
  --tracking-heading: ${r.rhythm.headingTracking}em;
  --tracking-body: ${r.rhythm.bodyTracking}em;

  /* Fluid type scale: ${r.scale.minViewport}px → ${r.scale.maxViewport}px */
${r.steps.map((s) => `  --text-${s.name}: ${s.clamp};`).join("\n")}
}

body {
  font-family: var(--font-body);
  font-size: var(--text-base);
  font-weight: var(--font-weight-body);
  line-height: var(--leading-body);
  letter-spacing: var(--tracking-body);${featureLine}
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  font-weight: var(--font-weight-heading);
  line-height: var(--leading-heading);
  letter-spacing: var(--tracking-heading);
}

h1 { font-size: var(--text-4xl); }
h2 { font-size: var(--text-3xl); }
h3 { font-size: var(--text-2xl); }
h4 { font-size: var(--text-xl); }
h5 { font-size: var(--text-lg); }
h6 { font-size: var(--text-base); }
small { font-size: var(--text-sm); }
`;
}

function tailwind(r: Resolved): string {
  return `/* Tailwind CSS v4 — paste into your main stylesheet */
@import "tailwindcss";
@import url("${googleFontsCssUrl(uniqueFonts(r))}");

@theme {
  --font-heading: ${fontStack(r.heading.family, r.heading.category)};
  --font-body: ${fontStack(r.body.family, r.body.category)};

${r.steps
  .map((s) => {
    const leading = s.step > 0 ? r.rhythm.headingLineHeight : r.rhythm.bodyLineHeight;
    return `  --text-${s.name}: ${s.clamp};\n  --text-${s.name}--line-height: ${leading};`;
  })
  .join("\n")}

  --tracking-heading: ${r.rhythm.headingTracking}em;
}

/* Usage: <h1 class="font-heading text-4xl tracking-heading">…</h1> */
`;
}

function scss(r: Resolved): string {
  return `@use "sass:map";

$font-heading: ${fontStack(r.heading.family, r.heading.category)};
$font-body: ${fontStack(r.body.family, r.body.category)};

$font-weight-heading: ${r.rhythm.headingWeight};
$font-weight-body: ${r.rhythm.bodyWeight};
$leading-heading: ${r.rhythm.headingLineHeight};
$leading-body: ${r.rhythm.bodyLineHeight};
$tracking-heading: ${r.rhythm.headingTracking}em;
$tracking-body: ${r.rhythm.bodyTracking}em;

$type-scale: (
${r.steps.map((s) => `  "${s.name}": ${s.clamp},`).join("\n")}
);

@function text($step) {
  @return map.get($type-scale, $step);
}

@mixin heading($step: "2xl") {
  font-family: $font-heading;
  font-size: text($step);
  font-weight: $font-weight-heading;
  line-height: $leading-heading;
  letter-spacing: $tracking-heading;
}

@mixin body($step: "base") {
  font-family: $font-body;
  font-size: text($step);
  font-weight: $font-weight-body;
  line-height: $leading-body;
  letter-spacing: $tracking-body;
}
`;
}

function react(r: Resolved): string {
  const sizes = r.steps.map((s) => `    "${s.name}": "${s.clamp}",`).join("\n");
  return `// typography.ts — generated by DesignHub
export const typography = {
  fonts: {
    heading: ${JSON.stringify(fontStack(r.heading.family, r.heading.category))},
    body: ${JSON.stringify(fontStack(r.body.family, r.body.category))},
  },
  weights: { heading: ${r.rhythm.headingWeight}, body: ${r.rhythm.bodyWeight} },
  leading: { heading: ${r.rhythm.headingLineHeight}, body: ${r.rhythm.bodyLineHeight} },
  tracking: { heading: "${r.rhythm.headingTracking}em", body: "${r.rhythm.bodyTracking}em" },
  sizes: {
${sizes}
  },
} as const;

export type TypeStep = keyof typeof typography.sizes;

export const googleFontsHref = ${JSON.stringify(googleFontsCssUrl(uniqueFonts(r)))};

export function headingStyle(step: TypeStep = "2xl") {
  return {
    fontFamily: typography.fonts.heading,
    fontSize: typography.sizes[step],
    fontWeight: typography.weights.heading,
    lineHeight: typography.leading.heading,
    letterSpacing: typography.tracking.heading,
  } as const;
}

export function bodyStyle(step: TypeStep = "base") {
  return {
    fontFamily: typography.fonts.body,
    fontSize: typography.sizes[step],
    fontWeight: typography.weights.body,
    lineHeight: typography.leading.body,
    letterSpacing: typography.tracking.body,
  } as const;
}
`;
}

export function typographyTokens(r: Resolved) {
  const dimension = (px: number) => ({ value: Math.round((px / 16) * 10000) / 10000, unit: "rem" });
  return {
    font: {
      family: {
        heading: { $type: "fontFamily", $value: [r.heading.family, r.heading.category] },
        body: { $type: "fontFamily", $value: [r.body.family, r.body.category] },
      },
      weight: {
        heading: { $type: "fontWeight", $value: r.rhythm.headingWeight },
        body: { $type: "fontWeight", $value: r.rhythm.bodyWeight },
      },
      size: Object.fromEntries(
        r.steps.map((s) => [
          s.name,
          {
            $type: "dimension",
            $value: dimension(s.maxPx),
            $extensions: { "dev.designhub.fluid": { min: dimension(s.minPx), max: dimension(s.maxPx), css: s.clamp } },
          },
        ]),
      ),
      lineHeight: {
        heading: { $type: "number", $value: r.rhythm.headingLineHeight },
        body: { $type: "number", $value: r.rhythm.bodyLineHeight },
      },
      letterSpacing: {
        heading: { $type: "dimension", $value: { value: r.rhythm.headingTracking, unit: "em" } },
        body: { $type: "dimension", $value: { value: r.rhythm.bodyTracking, unit: "em" } },
      },
    },
  };
}

export function typographyExports(input: TypographyExportInput): ExportFormat[] {
  const r = resolve(input);
  return [
    { id: "css", label: "CSS", filename: "typography.css", language: "css", code: css(r) },
    { id: "tailwind", label: "Tailwind", filename: "tailwind.css", language: "css", code: tailwind(r) },
    { id: "scss", label: "SCSS", filename: "_typography.scss", language: "scss", code: scss(r) },
    { id: "react", label: "React", filename: "typography.ts", language: "ts", code: react(r) },
    {
      id: "json",
      label: "JSON tokens",
      filename: "typography.tokens.json",
      language: "json",
      code: `${JSON.stringify(typographyTokens(r), null, 2)}\n`,
    },
    {
      id: "html",
      label: "HTML embed",
      filename: "fonts.html",
      language: "html",
      code: `${googleFontsEmbed(uniqueFonts(r))}\n`,
    },
  ];
}
